version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: reading_tracker_db
    restart: always
    environment:
      POSTGRES_USER: reading_user
      POSTGRES_PASSWORD: reading_pass
      POSTGRES_DB: reading_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reading_user -d reading_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: